'use client';

import { ReactNode, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  Activity, AlertTriangle, BarChart3, Bot, Check, ChevronRight, CircleDollarSign,
  CreditCard, FileClock, Gauge, HelpCircle, KeyRound, LayoutDashboard, LogOut, Menu,
  PlugZap, ScrollText, Settings, ShieldCheck, ShieldEllipsis, Siren,
  Users, Wrench, X, XCircle, Zap,
} from 'lucide-react';
import { API_BASE, api, asList, Me } from '@/lib/api';

type Json = Record<string, unknown>;
type FieldOption=string|{value:string;label:string};
type Field = { name:string; label:string; type?:'text'|'number'|'textarea'|'select'|'checkbox'|'json'; required?:boolean; options?:FieldOption[]; placeholder?:string; defaultValue?:string|number|boolean };
type Nav = { id:string; label:string; icon:typeof Activity; group:string };

const navigation:Nav[] = [
  {id:'overview',label:'Overview',icon:LayoutDashboard,group:'Monitor'}, {id:'agents',label:'Agents',icon:Bot,group:'Manage'},
  {id:'tools',label:'Tools',icon:Wrench,group:'Manage'}, {id:'policies',label:'Policies',icon:ShieldCheck,group:'Manage'},
  {id:'approvals',label:'Approvals',icon:ShieldEllipsis,group:'Operations'}, {id:'requests',label:'Requests',icon:Activity,group:'Operations'},
  {id:'audit',label:'Audit',icon:FileClock,group:'Operations'}, {id:'risks',label:'Risks',icon:Siren,group:'Operations'},
  {id:'budgets',label:'Budgets',icon:CircleDollarSign,group:'Controls'}, {id:'analytics',label:'Analytics',icon:BarChart3,group:'Monitor'},
  {id:'integrations',label:'Integrations',icon:PlugZap,group:'Configure'}, {id:'api-keys',label:'API keys',icon:KeyRound,group:'Configure'},
  {id:'team',label:'Team',icon:Users,group:'Configure'}, {id:'billing',label:'Billing',icon:CreditCard,group:'Account'},
  {id:'settings',label:'Settings',icon:Settings,group:'Account'}, {id:'help',label:'Feature guide',icon:HelpCircle,group:'Account'},
];

const help:Record<string,{summary:string;detail:string}> = {
  overview:{summary:'Your live security posture at a glance.',detail:'Combines enforcement volume, pending human decisions, risk and spend. All numbers come directly from the overview API.'},
  agents:{summary:'Register and control protected AI runtimes.',detail:'An agent identifies a workload, its framework, model provider and operating environment. Issue scoped credentials after creation and suspend or revoke access instantly.'},
  tools:{summary:'Catalog capabilities an agent may invoke.',detail:'Mark financial, destructive and sensitive-data capabilities so policies can make decisions from reliable tool metadata. Adapters define how AgentGuard connects.'},
  policies:{summary:'Express guardrails and test before publishing.',detail:'Policies are prioritized documents evaluated before protected actions. Simulation evaluates a candidate document against supplied facts without changing enforcement.'},
  approvals:{summary:'Resolve actions requiring human judgment.',detail:'Approve or reject queued requests. Decisions are sent with CSRF protection and become part of the audit trail.'},
  requests:{summary:'Inspect every protected action request.',detail:'Shows the execution request lifecycle and associated agent, tool, decision, risk, and timing returned by the API.'},
  audit:{summary:'Searchable compliance evidence.',detail:'Immutable security events can be inspected here and exported as JSON or CSV for incident response or compliance workflows.'},
  risks:{summary:'Focus investigation on high-risk activity.',detail:'This view filters the live request stream to risky, denied, blocked, or flagged actions; it does not calculate client-side risk scores.'},
  budgets:{summary:'Enforce cost ceilings and request velocity.',detail:'Budgets limit monetary usage by scope and period. Rate limits cap request counts in fixed windows to contain runaway automation.'},
  analytics:{summary:'Analyze decisions, activity, and spend.',detail:'Uses the analytics endpoint for server-computed aggregates. Charts appear only when series data exists.'},
  integrations:{summary:'Connect external providers without exposing secrets.',detail:'Integration records hold non-secret configuration and a secret reference. Stored credentials can be revoked separately.'},
  'api-keys':{summary:'Review and revoke issued credentials.',detail:'Secrets are never retrieved again. A newly issued agent key is displayed exactly once; this page lists metadata and supports revocation.'},
  team:{summary:'Organize access by people, teams and workspaces.',detail:'Invite members with roles, group agents and people into teams, and separate environments or business units with workspaces.'},
  billing:{summary:'Understand plan limits and manage subscription.',detail:'Usage is read from billing. Checkout and portal redirects are available only when Stripe is configured by the backend.'},
  settings:{summary:'Set organization-wide data and emergency controls.',detail:'Configure DLP handling and custom patterns. The kill switch immediately blocks matching scopes and should be reserved for containment.'},
};

export function Dashboard({me,onLogout}:{me:Me & {csrf_token:string};onLogout:()=>void}) {
  const [active,setActive]=useState(()=>typeof location==='undefined'?'overview':location.hash.slice(1)||'overview');
  const [mobile,setMobile]=useState(false); const item=navigation.find(x=>x.id===active)||navigation[0];
  const go=(id:string)=>{setActive(id);setMobile(false);location.hash=id};
  return <div className="min-h-screen bg-[#070c16]">
    <aside className={`fixed inset-y-0 left-0 z-30 w-64 border-r border-slate-800 bg-[#09101d] transition-transform lg:translate-x-0 ${mobile?'translate-x-0':'-translate-x-full'}`}>
      <div className="flex h-17 items-center justify-between border-b border-slate-800 px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-lime text-ink"><ShieldCheck size={20}/></span><b>AgentGuard</b></div><button className="lg:hidden" onClick={()=>setMobile(false)}><X/></button></div>
      <nav className="scrollbar h-[calc(100vh-145px)] overflow-y-auto p-3">{[...new Set(navigation.map(x=>x.group))].map(group=><div className="mb-4" key={group}><p className="px-3 py-2 text-[10px] font-bold uppercase tracking-[.2em] text-slate-600">{group}</p>{navigation.filter(x=>x.group===group).map(n=><button key={n.id} onClick={()=>go(n.id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm ${active===n.id?'bg-lime/10 text-lime':'text-slate-400 hover:bg-slate-800/60 hover:text-white'}`}><n.icon size={17}/>{n.label}</button>)}</div>)}</nav>
      <div className="absolute bottom-0 w-full border-t border-slate-800 p-3"><button onClick={()=>go('settings')} className="flex w-full items-center gap-3 rounded-xl p-2 text-left hover:bg-slate-800"><span className="grid h-8 w-8 place-items-center rounded-lg bg-indigo-500/20 text-xs font-bold text-indigo-200">{initials(me.user.name)}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium">{me.user.name}</span><span className="block truncate text-[10px] text-slate-500">{me.organization.name}</span></span><ChevronRight size={14}/></button></div>
    </aside>
    {mobile&&<button aria-label="Close menu" className="fixed inset-0 z-20 bg-black/60 lg:hidden" onClick={()=>setMobile(false)}/>} 
    <div className="lg:pl-64"><header className="sticky top-0 z-10 flex h-17 items-center gap-4 border-b border-slate-800 bg-[#070c16]/90 px-5 py-4 backdrop-blur xl:px-8"><button className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></button><div><h1 className="font-semibold">{item.label}</h1><p className="hidden text-xs text-slate-500 sm:block">{help[item.id]?.summary||'AgentGuard control plane'}</p></div><div className="ml-auto flex items-center gap-2"><span className="hidden rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-400 md:inline">{me.organization.plan}</span><button title="Sign out" className="btn btn-secondary !p-2" onClick={async()=>{await api.post('/auth/logout',{},me.csrf_token);sessionStorage.removeItem('agentguard_csrf');onLogout()}}><LogOut size={16}/></button></div></header>
      <main className="mx-auto max-w-[1500px] p-5 xl:p-8"><Page id={active} me={me}/></main>
    </div>
  </div>
}

function Page({id,me}:{id:string;me:Me & {csrf_token:string}}) {
  switch(id){
    case 'overview': return <Overview/>; case 'analytics': return <Analytics/>;
    case 'agents': return <Agents me={me}/>; case 'tools': return <CrudPage me={me} title="Tools" endpoint="/tools" description={help.tools.detail} fields={toolFields}/>;
    case 'policies': return <Policies me={me}/>; case 'approvals': return <Approvals me={me}/>;
    case 'requests': return <DataLog title="Protected requests" endpoint="/requests" description={help.requests.detail}/>;
    case 'audit': return <Audit/>; case 'risks': return <Risks/>; case 'budgets': return <Budgets me={me}/>;
    case 'integrations': return <CrudPage me={me} title="Integrations" endpoint="/integrations" description={help.integrations.detail} fields={integrationFields}/>;
    case 'api-keys': return <Credentials me={me}/>; case 'team': return <Team me={me}/>; case 'billing': return <Billing me={me}/>;
    case 'settings': return <OrganizationSettings me={me}/>; case 'help': return <FeatureGuide/>; default:return <Overview/>;
  }
}

function Overview(){const q=useQuery({queryKey:['overview'],queryFn:()=>api.get<Json>('/overview')}); if(q.isLoading)return <Loading/>; if(q.error)return <ErrorState error={q.error} retry={()=>q.refetch()}/>; const d=q.data||{}; const stats=[['Active agents',d.active_agents,Bot],['Protected actions',d.protected_actions,ShieldCheck],['Blocked actions',d.blocked_actions,XCircle],['Pending approvals',d.pending_approvals,ShieldEllipsis],['High risk',d.high_risk_actions,AlertTriangle],['Monthly spend',money(d.monthly_spend_minor),CircleDollarSign],['Security score',d.security_score==null?'—':`${d.security_score}%`,Gauge]] as const;return <div className="fade space-y-6"><Guide text={help.overview.detail}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,Icon])=><div className="card p-5" key={label}><div className="flex items-center justify-between text-slate-400"><span className="text-sm">{label}</span><Icon size={18}/></div><p className="mt-4 text-3xl font-semibold">{value==null?'—':String(value)}</p></div>)}</div><div className="grid gap-5 xl:grid-cols-2"><JsonPanel title="Decision counts" value={d.decision_counts}/><Series title="Daily protected actions" value={d.daily_actions}/></div></div>}
function Analytics(){const q=useQuery({queryKey:['analytics'],queryFn:()=>api.get<Json>('/analytics')});if(q.isLoading)return <Loading/>;if(q.error)return <ErrorState error={q.error} retry={()=>q.refetch()}/>;const d=q.data||{};return <div className="space-y-5"><Guide text={help.analytics.detail}/><div className="grid gap-5 lg:grid-cols-2">{Object.entries(d).map(([k,v])=><Series key={k} title={human(k)} value={v}/>)}</div>{!Object.keys(d).length&&<Empty title="No analytics yet" text="Aggregates will appear after protected actions are evaluated."/>}</div>}

function Agents({me}:{me:Me & {csrf_token:string}}) {
  const q=useQuery({queryKey:['/agents'],queryFn:()=>api.get<unknown>('/agents')});
  const qc=useQueryClient();
  const [creating,setCreating]=useState(false);
  const [editing,setEditing]=useState<Json|null>(null);
  const [issuing,setIssuing]=useState<Json|null>(null);
  const [secret,setSecret]=useState('');
  const mutate=useMutation({
    mutationFn:({id,status}:{id:string;status:string})=>api.post(`/agents/${id}/status`,{status},me.csrf_token),
    onSuccess:()=>qc.invalidateQueries({queryKey:['/agents']}),
  });
  const remove=useMutation({
    mutationFn:(id:string)=>api.delete(`/agents/${id}`,me.csrf_token),
    onSuccess:()=>qc.invalidateQueries({queryKey:['/agents']}),
  });
  const fields=agentFields.map(f=>f.name==='workspace_id'?{...f,type:'select' as const,options:me.workspaces.map(w=>({value:w.id,label:w.name})),defaultValue:me.workspaces[0]?.id}:f.name==='environment'?{...f,defaultValue:me.workspaces[0]?.environment||'development'}:f);
  return <div className="space-y-5">
    <Guide text={help.agents.detail}/>
    <SectionHead title="Protected agents" action={<button disabled={!me.workspaces.length} title={me.workspaces.length?'':'Create a workspace first'} className="btn btn-primary disabled:opacity-35" onClick={()=>setCreating(true)}>Add agent</button>}/>{!me.workspaces.length&&<p className="rounded-xl border border-amber-700/50 bg-amber-950/20 p-4 text-sm text-amber-200">Create a workspace before registering an agent.</p>}
    {(mutate.error||remove.error)&&<p role="alert" className="text-sm text-red-300">{(mutate.error||remove.error)?.message}</p>}
    {secret&&<SecretReveal value={secret} close={()=>setSecret('')}/>}
    {q.isLoading?<Loading/>:q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:<Cards items={asList<Json>(q.data)} empty="No agents registered" render={a=><>
      <CardTitle item={a}/><KeyValues item={a} keys={['framework','model_provider','environment','status']}/>
      <div className="mt-4 flex flex-wrap gap-2">
        <button className="btn btn-secondary text-xs" onClick={()=>setIssuing(a)}>Issue credential</button>
        <button className="btn btn-secondary text-xs" onClick={()=>setEditing(a)}>Edit</button>
        {['active','suspended','revoked'].map(s=><button key={s} disabled={mutate.isPending||a.status===s} className="btn btn-secondary text-xs disabled:opacity-30" onClick={()=>mutate.mutate({id:String(a.id),status:s})}>{human(s)}</button>)}
        <button className="btn btn-danger text-xs" onClick={()=>{if(confirm('Archive this agent and revoke all its credentials?'))remove.mutate(String(a.id))}}>Archive</button>
      </div>
    </>}/>}
    {creating&&<FormModal title="Register agent" endpoint="/agents" fields={fields} csrf={me.csrf_token} close={()=>setCreating(false)} queryKey="/agents"/>}
    {editing&&<EditAgent agent={editing} csrf={me.csrf_token} close={()=>setEditing(null)}/>}
    {issuing&&<IssueCredential agent={issuing} csrf={me.csrf_token} close={()=>setIssuing(null)} reveal={key=>{setSecret(key);setIssuing(null)}}/>}
  </div>
}
function EditAgent({agent,csrf,close}:{agent:Json;csrf:string;close:()=>void}) {
  const qc=useQueryClient();
  const [validation,setValidation]=useState('');
  const fields=agentFields.filter(f=>!['workspace_id','environment'].includes(f.name));
  const m=useMutation({mutationFn:(body:Json)=>api.patch(`/agents/${agent.id}`,body,csrf),onSuccess:()=>{qc.invalidateQueries({queryKey:['/agents']});close()}});
  return <Modal title="Edit agent" close={close}><form className="space-y-4" onSubmit={e=>{e.preventDefault();try{m.mutate(readForm(e.currentTarget,fields))}catch(err){setValidation(String(err))}}}>
    {fields.map(f=><Input key={f.name} field={f} value={agent[f.name]}/>)}
    {(m.error||validation)&&<p role="alert" className="text-red-300">{m.error?.message||validation}</p>}
    <button disabled={m.isPending} className="btn btn-primary">Save changes</button>
  </form></Modal>
}
function IssueCredential({agent,csrf,close,reveal}:{agent:Json;csrf:string;close:()=>void;reveal:(key:string)=>void}) {
  const tools=useQuery({queryKey:['/tools'],queryFn:()=>api.get<unknown>('/tools')});
  const m=useMutation({mutationFn:(body:Json)=>api.post<{api_key:string}>(`/agents/${agent.id}/credentials`,body,csrf),onSuccess:r=>reveal(r.api_key)});
  return <Modal title="Issue scoped agent credential" close={close}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);m.mutate({environment:agent.environment,expires_in_days:Number(f.get('expires_in_days')),tools:f.getAll('tools')})}} className="space-y-4">
    <p className="text-sm text-slate-400">Credential environment: <b className="text-white">{String(agent.environment)}</b>. Select permitted tool names. Empty scopes allow no tools.</p>
    <label><span className="label">Expires in days</span><input className="field" name="expires_in_days" type="number" min="1" max="3650" defaultValue="30" required/></label>
    <fieldset><legend className="label">Allowed tools</legend>{tools.isLoading?<p className="text-sm text-slate-500">Loading tools…</p>:tools.error?<p className="text-red-300">{tools.error.message}</p>:asList<Json>(tools.data).map(t=><label className="mb-2 flex items-center gap-3 text-sm" key={String(t.id)}><input type="checkbox" name="tools" value={String(t.name)} className="accent-lime"/>{String(t.name)}</label>)}</fieldset>
    {m.error&&<p role="alert" className="text-red-300">{m.error.message}</p>}
    <button disabled={m.isPending||tools.isError} className="btn btn-primary">Generate credential</button>
  </form></Modal>
}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}) {
  return <div role="dialog" aria-modal="true" aria-label={title} className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><section className="card scrollbar max-h-[90vh] w-full max-w-xl overflow-auto p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button aria-label="Close dialog" onClick={close}><X/></button></div>{children}</section></div>
}

function Policies({me}:{me:Me & {csrf_token:string}}){const [sim,setSim]=useState(false);return <div className="space-y-5"><Guide text={help.policies.detail}/><div className="flex justify-end"><button onClick={()=>setSim(true)} className="btn btn-secondary"><Zap size={16}/>Simulate policy</button></div><CrudPage me={me} title="Policy library" endpoint="/policies" fields={policyFields}/>{sim&&<Simulation csrf={me.csrf_token} close={()=>setSim(false)}/>}</div>}
function Approvals({me}:{me:Me & {csrf_token:string}}){const q=useQuery({queryKey:['approvals'],queryFn:()=>api.get<unknown>('/approvals')});const qc=useQueryClient();const m=useMutation({mutationFn:({id,decision}:{id:string;decision:string})=>api.post(`/approvals/${id}/decide`,{decision},me.csrf_token),onSuccess:()=>qc.invalidateQueries({queryKey:['approvals']})});const items=asList<Json>(q.data);return <div className="space-y-5"><Guide text={help.approvals.detail}/>{q.isLoading?<Loading/>:q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:<Cards items={items} empty="Approval queue is clear" render={a=><><CardTitle item={a}/><KeyValues item={a}/><div className="mt-4 flex gap-2"><button disabled={m.isPending} className="btn btn-primary" onClick={()=>m.mutate({id:String(a.id),decision:'approve'})}><Check size={16}/>Approve</button><button disabled={m.isPending} className="btn btn-danger" onClick={()=>m.mutate({id:String(a.id),decision:'reject'})}><X size={16}/>Reject</button></div></>}/>}</div>}

function DataLog({title,endpoint,description}:{title:string;endpoint:string;description?:string}){const q=useQuery({queryKey:[endpoint],queryFn:()=>api.get<unknown>(endpoint)});const items=asList<Json>(q.data);return <div className="space-y-5">{description&&<Guide text={description}/>}<SectionHead title={title}/>{q.isLoading?<Loading/>:q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:<Table items={items}/>}</div>}
function Audit(){async function download(format:'json'|'csv'){const r=await fetch(`${API_BASE}/api/v1/audit/export?format=${format}`,{credentials:'include'});if(!r.ok)throw new Error(`Export failed (${r.status})`);const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`agentguard-audit.${format}`;a.click();URL.revokeObjectURL(url)}return <div className="space-y-5"><Guide text={help.audit.detail}/><div className="flex justify-end gap-2"><button className="btn btn-secondary" onClick={()=>download('csv')}>Export CSV</button><button className="btn btn-secondary" onClick={()=>download('json')}>Export JSON</button></div><DataLog title="Audit events" endpoint="/audit"/></div>}
function Risks(){const q=useQuery({queryKey:['requests'],queryFn:()=>api.get<unknown>('/requests')});const risk=asList<Json>(q.data).filter(x=>Number(x.risk_score)>=70 || ['block','blocked','deny','denied'].includes(String(x.decision).toLowerCase()));return <div className="space-y-5"><Guide text={help.risks.detail}/>{q.isLoading?<Loading/>:q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:<Table items={risk} empty="No risky activity reported"/>}</div>}

function Budgets({me}:{me:Me & {csrf_token:string}}){return <div className="space-y-8"><Guide text={help.budgets.detail}/><CrudPage me={me} title="Budgets" endpoint="/budgets" fields={budgetFields}/><CrudPage me={me} title="Rate limits" endpoint="/rate-limits" fields={rateLimitFields}/></div>}
function Credentials({me}:{me:Me & {csrf_token:string}}){const q=useQuery({queryKey:['credentials'],queryFn:()=>api.get<unknown>('/credentials')});const qc=useQueryClient();const del=useMutation({mutationFn:(id:string)=>api.delete(`/credentials/${id}`,me.csrf_token),onSuccess:()=>qc.invalidateQueries({queryKey:['credentials']})});return <div className="space-y-5"><Guide text={help['api-keys'].detail}/>{q.isLoading?<Loading/>:q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:<Cards items={asList<Json>(q.data)} empty="No active credentials" render={x=><><CardTitle item={x}/><KeyValues item={x}/><button className="btn btn-danger mt-4" onClick={()=>del.mutate(String(x.id))}>Revoke</button></>}/>}</div>}
function Team({me}:{me:Me & {csrf_token:string}}){return <div className="space-y-8"><Guide text={help.team.detail}/><DataLog title="Organization members" endpoint="/members"/><CreateInline title="Invite a member" endpoint="/invitations" csrf={me.csrf_token} fields={inviteFields}/><CrudPage me={me} title="Teams" endpoint="/teams" fields={teamFields.map(f=>f.name==='workspace_id'?{...f,type:'select' as const,options:me.workspaces.map(w=>({value:w.id,label:w.name})),defaultValue:me.workspaces[0]?.id}:f)}/><CrudPage me={me} title="Workspaces" endpoint="/workspaces" fields={[{name:'name',label:'Workspace name',required:true},{name:'environment',label:'Environment',type:'select',options:['development','staging','production'],required:true}]}/></div>}

function Billing({me}:{me:Me & {csrf_token:string}}){const q=useQuery({queryKey:['billing'],queryFn:()=>api.get<Json>('/billing')});const [error,setError]=useState('');async function redirect(path:string,body?:unknown){setError('');try{const r=await api.post<{url:string}>(path,body,me.csrf_token);if(!r.url)throw new Error('Billing provider did not return a checkout URL');location.assign(r.url)}catch(e){setError(e instanceof Error?e.message:'Billing request failed')}}if(q.isLoading)return <Loading/>;if(q.error)return <ErrorState error={q.error} retry={()=>q.refetch()}/>;const d=q.data||{};const configured=d.configured===true;return <div className="space-y-5"><Guide text={help.billing.detail}/><div className="card p-6"><p className="text-sm text-slate-400">Current plan</p><p className="mt-2 text-3xl font-semibold capitalize">{String(d.plan||'Not reported')}</p><div className="mt-5 grid gap-4 md:grid-cols-2"><JsonPanel title="Usage" value={d.usage}/><JsonPanel title="Limits" value={d.limits}/></div>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}<div className="mt-6 flex flex-wrap gap-2"><button disabled={!configured} title={configured?'':'Stripe is not configured'} className="btn btn-primary disabled:opacity-35" onClick={()=>redirect('/billing/checkout',{plan:'pro'})}>Upgrade to Pro</button><button disabled={!configured} className="btn btn-secondary disabled:opacity-35" onClick={()=>redirect('/billing/checkout',{plan:'team'})}>Choose Team</button><button disabled={!configured} className="btn btn-secondary disabled:opacity-35" onClick={()=>redirect('/billing/portal')}>Billing portal</button></div>{!configured&&<p className="mt-4 text-sm text-amber-300">Billing is unavailable until Stripe is configured on the API.</p>}</div></div>}

function OrganizationSettings({me}:{me:Me & {csrf_token:string}}){const q=useQuery({queryKey:['settings'],queryFn:()=>api.get<Json>('/settings')});const qc=useQueryClient();const m=useMutation({mutationFn:(body:Json)=>api.patch('/settings',body,me.csrf_token),onSuccess:()=>qc.invalidateQueries({queryKey:['settings']})});if(q.isLoading)return <Loading/>;return <div className="space-y-8"><Guide text={help.settings.detail}/>{q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:<EditSettings data={q.data||{}} save={x=>m.mutate(x)} busy={m.isPending}/>}<CreateInline title="Emergency kill switch" endpoint="/kill-switch" csrf={me.csrf_token} fields={killFields}/></div>}
function EditSettings({data,save,busy}:{data:Json;save:(x:Json)=>void;busy:boolean}){return <form className="card max-w-2xl space-y-4 p-6" onSubmit={e=>{e.preventDefault();save(readForm(e.currentTarget,settingsFields))}}><h2 className="font-semibold">Organization settings</h2>{settingsFields.map(f=><Input key={f.name} field={f} value={data[f.name]}/>) }<button className="btn btn-primary" disabled={busy}>Save settings</button></form>}

function FeatureGuide(){return <div className="space-y-5"><div><p className="text-sm text-lime">Product guide</p><h2 className="mt-2 text-2xl font-semibold">How AgentGuard’s features work</h2><p className="mt-2 text-slate-400">Each control has a distinct job in the path from agent intent to safe execution.</p></div><div className="grid gap-4 md:grid-cols-2">{navigation.filter(x=>help[x.id]).map(x=><article className="card p-5" key={x.id}><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-lime/10 text-lime"><x.icon size={18}/></span><h3 className="font-semibold">{x.label}</h3></div><p className="mt-4 text-sm font-medium text-slate-300">{help[x.id].summary}</p><p className="mt-2 text-sm leading-6 text-slate-500">{help[x.id].detail}</p></article>)}</div></div>}

function CrudPage({me,title,endpoint,fields,description}:{me:Me & {csrf_token:string};title:string;endpoint:string;fields:Field[];description?:string}){const q=useQuery({queryKey:[endpoint],queryFn:()=>api.get<unknown>(endpoint)});const [open,setOpen]=useState(false);return <section className="space-y-5">{description&&<Guide text={description}/>}<SectionHead title={title} action={<button className="btn btn-primary" onClick={()=>setOpen(true)}>Add {title.toLowerCase().replace(/s$/,'')}</button>}/>{q.isLoading?<Loading/>:q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:<Cards items={asList<Json>(q.data)} empty={`No ${title.toLowerCase()} configured`} render={x=><><CardTitle item={x}/><KeyValues item={x}/></>}/>} {open&&<FormModal title={`Create ${title.toLowerCase().replace(/s$/,'')}`} endpoint={endpoint} fields={fields} csrf={me.csrf_token} queryKey={endpoint} close={()=>setOpen(false)}/>}</section>}
function FormModal({title,endpoint,fields,csrf,queryKey,close}:{title:string;endpoint:string;fields:Field[];csrf?:string;queryKey:string;close:()=>void}){const qc=useQueryClient();const m=useMutation({mutationFn:(body:Json)=>api.post(endpoint,body,csrf),onSuccess:()=>{qc.invalidateQueries({queryKey:[queryKey]});close()}});return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={e=>{e.preventDefault();m.mutate(readForm(e.currentTarget,fields))}} className="card scrollbar max-h-[90vh] w-full max-w-xl overflow-auto p-6"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button type="button" onClick={close}><X/></button></div><div className="grid gap-4 sm:grid-cols-2">{fields.map(f=><Input key={f.name} field={f}/>)}</div>{m.error&&<p role="alert" className="mt-4 text-sm text-red-300">{m.error.message}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button><button disabled={m.isPending} className="btn btn-primary">{m.isPending?'Saving…':'Save'}</button></div></form></div>}
function CreateInline({title,endpoint,fields,csrf}:{title:string;endpoint:string;fields:Field[];csrf?:string}){const m=useMutation({mutationFn:(body:Json)=>api.post(endpoint,body,csrf)});return <form className="card p-6" onSubmit={e=>{e.preventDefault();m.mutate(readForm(e.currentTarget,fields))}}><h2 className="mb-5 font-semibold">{title}</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{fields.map(f=><Input field={f} key={f.name}/>)}</div>{m.error&&<p className="mt-3 text-sm text-red-300">{m.error.message}</p>}{m.isSuccess&&<p className="mt-3 text-sm text-lime">Saved successfully.</p>}<button className="btn btn-primary mt-5">Submit</button></form>}
function Simulation({csrf,close}:{csrf?:string;close:()=>void}){const m=useMutation({mutationFn:(body:Json)=>api.post('/policies/simulate',body,csrf)});const fields:Field[]=[{name:'document',label:'Policy document (JSON or YAML)',type:'textarea',required:true},{name:'facts',label:'Facts (JSON)',type:'json',required:true,defaultValue:'{}'}];return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form className="card w-full max-w-2xl p-6" onSubmit={e=>{e.preventDefault();m.mutate(readForm(e.currentTarget,fields))}}><div className="flex justify-between"><h2 className="text-xl font-semibold">Simulate policy</h2><button type="button" onClick={close}><X/></button></div><div className="mt-5 space-y-4">{fields.map(f=><Input field={f} key={f.name}/>)}</div>{m.error&&<p className="mt-4 text-red-300">{m.error.message}</p>}{m.data!==undefined&&<pre className="scrollbar mt-4 max-h-56 overflow-auto rounded-xl bg-black/30 p-4 text-xs text-lime">{JSON.stringify(m.data,null,2)}</pre>}<button className="btn btn-primary mt-5">Run simulation</button></form></div>}

function Input({field,value}:{field:Field;value?:unknown}){const initial=value??field.defaultValue??'';const defaultValue=field.type==='json'&&typeof initial==='object'?JSON.stringify(initial,null,2):String(initial);const common={name:field.name,required:field.required,defaultValue,placeholder:field.placeholder,className:'field'};return <label className={field.type==='textarea'||field.type==='json'?'sm:col-span-2':''}><span className="label">{field.label}{field.required?' *':''}</span>{field.type==='select'?<select {...common}>{field.options?.map(x=>{const value=typeof x==='string'?x:x.value;return <option key={value} value={value}>{typeof x==='string'?human(x):x.label}</option>})}</select>:field.type==='textarea'||field.type==='json'?<textarea {...common} rows={5}/>:field.type==='checkbox'?<input name={field.name} type="checkbox" defaultChecked={Boolean(value??field.defaultValue)} className="h-5 w-5 accent-lime"/>:<input {...common} type={field.type||'text'}/>}</label>}
function readForm(form:HTMLFormElement,fields:Field[]):Json{const fd=new FormData(form);const o:Json={};for(const f of fields){let v:unknown=f.type==='checkbox'?fd.has(f.name):fd.get(f.name);if(f.type==='number')v=Number(v);if(f.type==='json'){try{v=JSON.parse(String(v))}catch{throw new Error(`${f.label} must be valid JSON`)}} if(v!==''&&v!==null)o[f.name]=v;}return o}

function Cards({items,render,empty}:{items:Json[];render:(x:Json)=>ReactNode;empty:string}){if(!items.length)return <Empty title={empty} text="Data will appear here after it is created or received by the API."/>;return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((x,i)=><article className="card overflow-hidden p-5" key={String(x.id||i)}>{render(x)}</article>)}</div>}
function Table({items,empty='No records returned'}:{items:Json[];empty?:string}){if(!items.length)return <Empty title={empty} text="The API returned an empty collection."/>;const keys=[...new Set(items.flatMap(x=>Object.keys(x)))].filter(k=>!['document','config','input_schema','output_schema'].includes(k)).slice(0,7);return <div className="card scrollbar overflow-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b border-slate-700 text-xs uppercase tracking-wider text-slate-500">{keys.map(k=><th className="px-4 py-3" key={k}>{human(k)}</th>)}</tr></thead><tbody>{items.map((x,i)=><tr className="border-b border-slate-800 last:border-0 hover:bg-slate-800/30" key={String(x.id||i)}>{keys.map(k=><td className="max-w-64 truncate px-4 py-3 text-slate-300" key={k}>{display(x[k])}</td>)}</tr>)}</tbody></table></div>}
function CardTitle({item}:{item:Json}){return <div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{String(item.name||item.title||item.email||item.id||'Record')}</h3>{Boolean(item.description)&&<p className="mt-1 line-clamp-2 text-sm text-slate-500">{String(item.description)}</p>}</div>{Boolean(item.status)&&<span className="rounded-full border border-slate-700 px-2 py-1 text-[10px] uppercase text-slate-400">{String(item.status)}</span>}</div>}
function KeyValues({item,keys}:{item:Json;keys?:string[]}){const entries=(keys||Object.keys(item)).filter(k=>!['id','name','title','email','description','status'].includes(k)&&item[k]!=null).slice(0,6);return <dl className="mt-4 grid grid-cols-2 gap-3">{entries.map(k=><div key={k}><dt className="text-[10px] uppercase tracking-wide text-slate-600">{human(k)}</dt><dd className="mt-1 truncate text-xs text-slate-300" title={display(item[k])}>{display(item[k])}</dd></div>)}</dl>}
function SecretReveal({value,close}:{value:string;close:()=>void}){const [copied,setCopied]=useState(false);return <div className="rounded-xl border border-amber-700/60 bg-amber-950/30 p-5"><div className="flex justify-between"><div><h3 className="font-semibold text-amber-200">Copy this key now</h3><p className="mt-1 text-sm text-amber-200/60">For your security, it will not be shown again.</p></div><button onClick={close}><X/></button></div><code className="scrollbar mt-4 block overflow-auto rounded-lg bg-black/40 p-3 text-sm text-amber-100">{value}</code><button className="btn btn-secondary mt-3" onClick={async()=>{await navigator.clipboard.writeText(value);setCopied(true)}}>{copied?'Copied':'Copy key'}</button></div>}
function Guide({text}:{text:string}){return <div className="flex gap-3 rounded-xl border border-indigo-500/20 bg-indigo-500/5 p-4 text-sm text-indigo-100/75"><HelpCircle className="mt-0.5 shrink-0 text-indigo-300" size={17}/><p>{text}</p></div>}
function SectionHead({title,action}:{title:string;action?:ReactNode}){return <div className="flex items-center justify-between gap-4"><h2 className="text-xl font-semibold">{title}</h2>{action}</div>}
function Loading(){return <div className="card grid min-h-48 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-slate-700 border-t-lime"/></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="card grid min-h-48 place-items-center p-8 text-center"><div><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-slate-800 text-slate-500"><ScrollText size={20}/></div><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-500">{text}</p></div></div>}
function ErrorState({error,retry}:{error:Error;retry:()=>void}){return <div className="card border-red-900/60 p-6"><p className="font-semibold text-red-300">Could not load this view</p><p className="mt-2 text-sm text-slate-500">{error.message}</p><button className="btn btn-secondary mt-4" onClick={retry}>Try again</button></div>}
function JsonPanel({title,value}:{title:string;value:unknown}){return <div className="card p-5"><h3 className="text-sm font-medium text-slate-400">{title}</h3>{value&&typeof value==='object'?<div className="mt-4 space-y-2">{Object.entries(value as Json).map(([k,v])=><div className="flex justify-between gap-3 text-sm" key={k}><span className="text-slate-500">{human(k)}</span><b>{display(v)}</b></div>)}</div>:<p className="mt-5 text-2xl font-semibold">{value==null?'No data':display(value)}</p>}</div>}
function Series({title,value}:{title:string;value:unknown}){if(Array.isArray(value)&&value.length){const nums=value.map(x=>Number(typeof x==='object'&&x?Object.values(x as Json).find(v=>typeof v==='number')||0:x));const max=Math.max(...nums,1);return <div className="card p-5"><h3 className="text-sm font-medium text-slate-400">{title}</h3><div className="mt-5 flex h-36 items-end gap-1">{nums.slice(-32).map((n,i)=><div key={i} title={String(n)} className="min-w-1 flex-1 rounded-t bg-lime/70" style={{height:`${Math.max(3,n/max*100)}%`}}/>)}</div></div>}return <JsonPanel title={title} value={value}/>}
function display(v:unknown):string{if(v==null)return '—';if(typeof v==='object')return JSON.stringify(v);return String(v)} function human(s:string){return s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())} function money(v:unknown){return typeof v==='number'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100):'—'} function initials(n:string){return n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}

const agentFields:Field[]=[{name:'name',label:'Name',required:true},{name:'description',label:'Description'},{name:'framework',label:'Framework',required:true},{name:'model_provider',label:'Model provider',required:true},{name:'environment',label:'Environment',required:true,defaultValue:'development'},{name:'workspace_id',label:'Workspace ID',required:true},{name:'team_id',label:'Team ID'}];
const toolFields:Field[]=[{name:'name',label:'Name',required:true},{name:'provider',label:'Provider',required:true},{name:'description',label:'Description'},{name:'environment',label:'Environment',required:true},{name:'adapter',label:'Adapter',type:'select',options:['sdk','http','stripe','github','postgres','mcp'],required:true},{name:'financial',label:'Financial',type:'checkbox'},{name:'destructive',label:'Destructive',type:'checkbox'},{name:'sensitive_data',label:'Sensitive data',type:'checkbox'},{name:'input_schema',label:'Input schema (JSON)',type:'json',defaultValue:'{}'},{name:'output_schema',label:'Output schema (JSON)',type:'json',defaultValue:'{}'},{name:'config',label:'Adapter config (JSON)',type:'json',defaultValue:'{}'}];
const policyFields:Field[]=[{name:'name',label:'Name',required:true},{name:'priority',label:'Priority',type:'number',required:true,defaultValue:100},{name:'workspace_id',label:'Workspace ID'},{name:'document',label:'Policy document (JSON or YAML)',type:'textarea',required:true,defaultValue:'{}'}];
const budgetFields:Field[]=[{name:'name',label:'Name',required:true},{name:'scope',label:'Scope',type:'select',options:['organization','agent','team','tool','provider','workspace'],required:true},{name:'scope_id',label:'Scope ID'},{name:'period',label:'Period',type:'select',options:['action','daily','weekly','monthly'],required:true},{name:'limit_minor',label:'Limit (minor units)',type:'number',required:true},{name:'currency',label:'Currency',defaultValue:'USD',required:true}];
const rateLimitFields:Field[]=[{name:'scope',label:'Scope',type:'select',options:['organization','workspace','agent','tool'],required:true},{name:'scope_id',label:'Scope ID'},{name:'window_seconds',label:'Window (seconds)',type:'number',required:true},{name:'max_requests',label:'Maximum requests',type:'number',required:true}];
const integrationFields:Field[]=[{name:'provider',label:'Provider',type:'select',options:['stripe','github','slack','postgres','http','mcp','email','webhook'],required:true},{name:'name',label:'Name',required:true},{name:'secret_ref',label:'Secret reference'},{name:'config',label:'Configuration (JSON)',type:'json',defaultValue:'{}'}];
const inviteFields:Field[]=[{name:'email',label:'Email',required:true},{name:'role',label:'Role',type:'select',options:['member','approver','auditor','admin'],required:true}];
const teamFields:Field[]=[{name:'name',label:'Team name',required:true},{name:'workspace_id',label:'Workspace ID',required:true}];
const settingsFields:Field[]=[{name:'name',label:'Organization name',required:true},{name:'dlp_action',label:'DLP action',type:'select',options:['allow','warn','redact','approval','block'],required:true},{name:'custom_dlp_patterns',label:'Custom DLP patterns (JSON)',type:'json',defaultValue:'[]'}];
const killFields:Field[]=[{name:'scope',label:'Scope',type:'select',options:['organization','workspace','agent','team','tool','environment'],required:true},{name:'scope_id',label:'Scope ID'},{name:'active',label:'Active',type:'checkbox',defaultValue:true},{name:'reason',label:'Reason',required:true}];
